# Generated by Django 5.2.17 on 2025-02-25 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('service', 'Service'), ('anonymous', 'Anonymous')], default='user', max_length=32)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['succeeded', 'denied', 'failed'])), name='audit_outcome_valid'), models.CheckConstraint(condition=models.Q(('actor_kind__in', ['user', 'service', 'anonymous'])), name='audit_actor_kind_valid')],
            },
        ),
    ]
