# Generated by Django 5.2.17 on 2025-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trigger', models.CharField(choices=[('nightly', 'Nightly'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('cases', models.PositiveSmallIntegerField()),
                ('recall_at_5', models.FloatField()),
                ('recall_at_10', models.FloatField()),
                ('mrr', models.FloatField()),
                ('errors', models.PositiveSmallIntegerField(default=0)),
                ('misses', models.JSONField(blank=True, default=list)),
                ('important_misses', models.JSONField(blank=True, default=list)),
                ('models_used', models.JSONField(blank=True, default=dict)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('trigger__in', ['nightly', 'manual'])), name='evalrun_trigger_valid')],
            },
        ),
    ]
