# Generated by Django 5.2.17 on 2025-07-05 11:02

import chat.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('streaming', 'Streaming'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='complete', max_length=10)),
                ('answer_type', models.CharField(blank=True, choices=[('answered', 'Answered'), ('no_answer', 'Not found'), ('smalltalk', 'Small talk'), ('out_of_scope', 'Out of scope'), ('personal_record', 'Personal record'), ('error', 'Error')], max_length=16, null=True)),
                ('grounded', models.BooleanField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chat.message')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('title_source', models.CharField(choices=[('auto', 'Automatic'), ('user', 'Set by user')], default='auto', max_length=8)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='current_leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField()),
                ('reason', models.CharField(blank=True, choices=[('incorrect', 'Incorrect'), ('outdated', 'Outdated'), ('incomplete', 'Incomplete'), ('irrelevant', 'Irrelevant'), ('unclear', 'Unclear'), ('other', 'Other')], max_length=16, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('heading_path', models.CharField(blank=True, max_length=500)),
                ('snippet', models.CharField(blank=True, max_length=600)),
                ('category', models.CharField(blank=True, choices=[('admissions', 'Admissions'), ('fees_scholarships', 'Fees & scholarships'), ('hostel_campus_life', 'Hostels & campus life'), ('academic_calendar', 'Academic calendar'), ('courses_syllabus', 'Courses & syllabus'), ('rules_regulations', 'Rules & regulations'), ('departments', 'Departments'), ('faculty', 'Faculty'), ('placements', 'Placements'), ('notices', 'Notices'), ('about_contact', 'About & contact'), ('faq', 'FAQ'), ('other', 'Other')], max_length=32)),
                ('academic_year', models.CharField(blank=True, max_length=7)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('cited', models.BooleanField(default=False)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.chunk')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.document')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.message')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='UsageDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(db_index=True)),
                ('questions', models.PositiveIntegerField(default=0)),
                ('answers', models.PositiveIntegerField(default=0)),
                ('llm_calls', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.BigIntegerField(default=0)),
                ('completion_tokens', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('daily_question_limit', models.PositiveIntegerField(default=40)),
                ('global_daily_llm_calls', models.PositiveIntegerField(default=5000)),
                ('rerank_enabled', models.BooleanField(default=True)),
                ('auto_title_enabled', models.BooleanField(default=True)),
                ('starter_questions', models.JSONField(default=chat.models.default_starter_questions)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'chat settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='chat_settings_singleton')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_conversation_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['user', 'assistant'])), name='message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['complete', 'streaming', 'stopped', 'failed'])), name='message_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('answer_type__in', ['answered', 'no_answer', 'smalltalk', 'out_of_scope', 'personal_record', 'error']), ('answer_type__isnull', True), _connector='OR'), name='message_answer_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content__length__lte', 20000)), name='message_content_length'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'user'), _negated=True), ('answer_type__isnull', True), _connector='OR'), name='message_user_has_no_answer_type'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('conversation', 'client_request_id'), name='message_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived', 'is_pinned', '-last_message_at'], name='conversation_sidebar_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='conversation_title_trgm', opclasses=('gin_trgm_ops',)),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('title_source__in', ['auto', 'user'])), name='conversation_title_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', (-1, 1))), name='feedback_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['incorrect', 'outdated', 'incomplete', 'irrelevant', 'unclear', 'other']), ('reason__isnull', True), _connector='OR'), name='feedback_reason_valid'),
        ),
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['document'], name='source_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagesource',
            constraint=models.UniqueConstraint(fields=('message', 'position'), name='source_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='usagedaily',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='usage_user_day_unique'),
        ),
    ]
