# Generated by Django 5.2.17 on 2025-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='rerank_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
