# Generated by Django 5.2.17 on 2025-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rerank_off_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
