# Generated by Django 5.2.17 on 2025-08-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='require_approval',
            field=models.BooleanField(default=True),
        ),
    ]
