# Generated by Django 5.2.17 on 2025-08-09 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsettings_require_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('suggestion', 'Suggestion'), ('problem', 'Something isn’t working'), ('answers', 'Answer quality'), ('other', 'Other')], max_length=12)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=2000)),
                ('page', models.CharField(blank=True, max_length=200)),
                ('contact_ok', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['review_status', 'created_at'], name='sitefeedback_review_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['suggestion', 'problem', 'answers', 'other'])), name='sitefeedback_kind_valid'), models.CheckConstraint(condition=models.Q(('review_status__in', ['open', 'resolved', 'dismissed'])), name='sitefeedback_review_valid'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='sitefeedback_rating_valid')],
            },
        ),
    ]
