# Generated by Django 5.2.17 on 2026-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_shared_answer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_answer_type_valid',
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('answered', 'Answered'), ('no_answer', 'Not found'), ('smalltalk', 'Small talk'), ('out_of_scope', 'Out of scope'), ('personal_record', 'Personal record'), ('cached', 'Cached answer'), ('conversation', 'About the chat'), ('error', 'Error')], max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('answer_type__in', ['answered', 'no_answer', 'smalltalk', 'out_of_scope', 'personal_record', 'cached', 'conversation', 'error']), ('answer_type__isnull', True), _connector='OR'), name='message_answer_type_valid'),
        ),
    ]
