# Generated by Django 5.2.17 on 2025-08-09 12:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_document_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('fees_scholarships', 'Fees & scholarships'), ('hostel_campus_life', 'Hostels & campus life'), ('academic_calendar', 'Academic calendar'), ('courses_syllabus', 'Courses & syllabus'), ('rules_regulations', 'Rules & regulations'), ('departments', 'Departments'), ('faculty', 'Faculty'), ('placements', 'Placements'), ('notices', 'Notices'), ('about_contact', 'About & contact'), ('faq', 'FAQ'), ('other', 'Other')], default='notices', max_length=32)),
                ('importance', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important')], default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, max_length=2000)),
                ('answerable', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='knowledge.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_draft', 'publish_at'], name='notice_publish_idx'), models.Index(fields=['is_pinned', 'publish_at'], name='notice_pinned_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['admissions', 'fees_scholarships', 'hostel_campus_life', 'academic_calendar', 'courses_syllabus', 'rules_regulations', 'departments', 'faculty', 'placements', 'notices', 'about_contact', 'faq', 'other'])), name='notice_category_valid'), models.CheckConstraint(condition=models.Q(('importance__in', ['normal', 'important'])), name='notice_importance_valid'), models.CheckConstraint(condition=models.Q(('body__length__lte', 5000)), name='notice_body_length'), models.CheckConstraint(condition=models.Q(('link_url', ''), ('link_url__startswith', 'https://'), _connector='OR'), name='notice_link_url_https'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('publish_at')), _connector='OR'), name='notice_expires_after_publish', violation_error_message='The expiry must be after the publish time.')],
            },
        ),
    ]
