# Generated by Django 5.2.17 on 2026-10-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_counter', models.BigIntegerField(default=0)),
                ('recovery_codes', models.JSONField(blank=True, default=list)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_second_factor',
            },
        ),
        migrations.CreateModel(
            name='SecondFactorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_time', models.BigIntegerField()),
                ('verified_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_factor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_second_factor_session',
                'constraints': [models.UniqueConstraint(fields=('user', 'auth_time'), name='second_factor_session_unique')],
            },
        ),
    ]
