# Generated by Django 5.2.17 on 2025-07-16 20:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('html', 'HTML file'), ('url', 'Web page'), ('text', 'Text / FAQ'), ('crawler', 'Crawler import')], max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('storage_path', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('fees_scholarships', 'Fees & scholarships'), ('hostel_campus_life', 'Hostels & campus life'), ('academic_calendar', 'Academic calendar'), ('courses_syllabus', 'Courses & syllabus'), ('rules_regulations', 'Rules & regulations'), ('departments', 'Departments'), ('faculty', 'Faculty'), ('placements', 'Placements'), ('notices', 'Notices'), ('about_contact', 'About & contact'), ('faq', 'FAQ'), ('other', 'Other')], default='other', max_length=32)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('academic_year', models.CharField(blank=True, max_length=7)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='queued', max_length=16)),
                ('status_detail', models.CharField(blank=True, max_length=200)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('parser', models.CharField(choices=[('auto', 'Auto'), ('fast', 'Fast (text layer)'), ('smart', 'Smart (OCR + tables)')], default='auto', max_length=8)),
                ('contextualize', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('search_text', models.TextField()),
                ('heading_path', models.CharField(blank=True, max_length=500)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=768, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('fees_scholarships', 'Fees & scholarships'), ('hostel_campus_life', 'Hostels & campus life'), ('academic_calendar', 'Academic calendar'), ('courses_syllabus', 'Courses & syllabus'), ('rules_regulations', 'Rules & regulations'), ('departments', 'Departments'), ('faculty', 'Faculty'), ('placements', 'Placements'), ('notices', 'Notices'), ('about_contact', 'About & contact'), ('faq', 'FAQ'), ('other', 'Other')], max_length=32)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('is_current', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('fts', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('heading_path', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('search_text', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ('document', 'chunk_index'),
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='document_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'is_current'], name='document_category_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='document_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='document_title_trgm', opclasses=('gin_trgm_ops',)),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['pdf', 'docx', 'xlsx', 'csv', 'html', 'url', 'text', 'crawler'])), name='document_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['admissions', 'fees_scholarships', 'hostel_campus_life', 'academic_calendar', 'courses_syllabus', 'rules_regulations', 'departments', 'faculty', 'placements', 'notices', 'about_contact', 'faq', 'other'])), name='document_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'processing', 'ready', 'failed', 'disabled'])), name='document_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('parser__in', ['auto', 'fast', 'smart'])), name='document_parser_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('academic_year', ''), ('academic_year__regex', '^\\d{4}-\\d{2}$'), _connector='OR'), name='document_academic_year_format'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('source_url', ''), ('source_url__startswith', 'https://'), _connector='OR'), name='document_source_url_https'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(condition=models.Q(('is_searchable', True)), ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=('halfvec_cosine_ops',)),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts'], name='chunk_fts_gin'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['category', 'is_current'], name='chunk_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='chunk_unique_index'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['admissions', 'fees_scholarships', 'hostel_campus_life', 'academic_calendar', 'courses_syllabus', 'rules_regulations', 'departments', 'faculty', 'placements', 'notices', 'about_contact', 'faq', 'other'])), name='chunk_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.CheckConstraint(condition=models.Q(('content__length__lte', 12000)), name='chunk_content_length'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.CheckConstraint(condition=models.Q(('page_start__isnull', True), ('page_end__isnull', True), ('page_end__gte', models.F('page_start')), _connector='OR'), name='chunk_page_range_valid'),
        ),
    ]
