# Generated by Django 5.2.17 on 2025-07-30 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('effective_date__isnull', True), ('valid_until__gte', models.F('effective_date')), _connector='OR'), name='document_valid_until_after_effective', violation_error_message='"Valid until" cannot be before the effective date.'),
        ),
    ]
